apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: LoadBalancer
  ports:
  - name: mydeployment-service-port
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
    