apiVersion: v1
kind: Service
metadata:
  name: deployment-lb-service
spec:
  type: LoadBalancer
  selector:
    app: myapp3
  ports:
    - name: http
      port: 8091
      targetPort: 80 #container port
