apiVersion: v1
kind: Service
metadata:
  name: mydeployment-service
  namespace: default
spec:
  selector:
    app: myapp3
  type: LoadBalancer
  ports:
  - name: mydeployment-service-port
    protocol: TCP
    port: 80
    targetPort: 80
    