apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
type: Opaque
data:
  Conection_String: U2VydmVyPXRjcDppdGd1dHNzZXJ2ZXIuZGF0YWJhc2Uud2luZG93cy5uZXQsMTQzMztJbml0aWFsIENhdGFsb2c9eW91cmRhdGFiYXNlO1BlcnNpc3QgU2VjdXJpdHkgSW5mbz1GYWxzZTtVc2VyIElEPXZpa2FzaDtQYXNzd29yZD1QYXNzd29yZEAxdjtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9RmFsc2U7RW5jcnlwdD1UcnVlO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9RmFsc2U7Q29ubmVjdGlvbiBUaW1lb3V0PTMwOw==
  